### ISSUE TITLE
data file for GCN example

### ISSUE THREAD

**Issue by thegodone** [iwatobipen/playground#2]
Dear Taka,

Can you share the solubility files for reproduce your model ?

best regards,

Guillaume

**Comment by thegodone** [comment]
i find them

**Comment by iwatobipen** [comment]
Hi Guillaume,
I hope you are doing well.
The data is got from rdkit_install_dir/Docs/Book/data .
And you found it ;)
Any suggestion and advices are greatly appreciated.
Kind regards,
Taka
